FROM node:14
# Create app directory
WORKDIR /usr/src/app
COPY ./package*.json ./
COPY ./tsconfig*.json ./
COPY . .
# USER node
# RUN npm ci --only=production
RUN npm install

RUN npm run build

COPY ./dist .

CMD [ "node", "dist/index.js" ]