# Stage 1 - Create a builder container
FROM node:14 as builder

ENV APP_HOME=/usr/src/app/
WORKDIR $APP_HOME

COPY package.json $APP_HOME/package.json
COPY tsconfig.json $APP_HOME/tsconfig.json
COPY craco.config.js $APP_HOME/craco.config.js

COPY src $APP_HOME/src
COPY public $APP_HOME/public

RUN npm install
RUN npm run build

# Stage 2 - Create a downsized production container
FROM nginx:1.17-alpine as production


COPY --from=builder /usr/src/app/build /usr/share/nginx/html